name: custom_permission_example
description: Demonstrates how to use the custom_permission plugin.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_permission:
    path: ../

flutter:
  uses-material-design: true